### ISSUE TITLE
Default Access Mode is reverse of what is described in docs

### ISSUE THREAD

**Issue by misshula** [Shopify/koa-shopify-auth#127]
When reading the Docs on Access Modes (Offline vs Online)

> Offline is the default access mode when none is specified.

as seen here: https://shopify.dev/apps/auth/access-modes#offline-access

> Online access must be explicitly requested during the authorization phase of OAuth.

as seen here: https://shopify.dev/apps/auth/access-modes#online-access

But, when using the Shopify CLI - it isn't obvious why you cannot make offline admin API calls... until you read this line: https://github.com/Shopify/koa-shopify-auth/blob/e70874f1cfc64bd01733fd98e1a14e45293bed83/src/auth/index.ts#L14

The fix is easy enough - be explicit:

```js
createShopifyAuth({
    accessMode: 'offline',
```

**Comment by paulomarg** [comment]
Thanks for pointing this out, we'll look into it!

**Comment by hugo4711** [comment]
After about 3 months of bugfixing, searching in forums and annoying our customers, this issue here popped up to our attention...

This is completely misleading because koa is deviating from the official shopify documentation.

koa should define 'offline' mode as default, just like the official documentation says...

**Comment by lukeclifton** [comment]
I raised this back in Feb 21 but the response was its `online` by default by design. Not entirely sure why this? Seems to trip quite a few people up.

https://github.com/Shopify/koa-shopify-auth/pull/49
