### ISSUE TITLE
New API version on Shopify, @shopify/koa-shopify-auth ApiVersion is outdated.

### ISSUE THREAD

**Issue by lukamusashvili** [Shopify/koa-shopify-auth#139]
Hi guys, I need to use Shopify's new API version. Could u pls update the library?
![1](https://user-images.githubusercontent.com/57059505/149292614-a3103675-8ae8-4cf6-aa96-48b996e15bd7.png)

**Comment by agustinsacco** [comment]
I am also stuck here. I have relayed the information to shopify since I am submitting a new app and they keep telling me to update thte api version but this package has not been updated.

Since this is the recommended package used in the boilerplate node app I want to continue using it instead of forking and upgrading myself (which will put me at a disadvantage in the future).

Not sure how to proceed since it doesnt look like this package is getting much support from Shopify tech team.

**Comment by lukamusashvili** [comment]
> Hi @lukamusashvili , I don't think it's because of this package, maybe you're problem is on "[shopify-api](https://github.com/Shopify/shopify-node-api)" package. If you want to use the latest version (2022-01), you can directly hardcode the version. Example below:
> 
> `Shopify.Context.initialize({ API_KEY: SHOPIFY_API_KEY, API_SECRET_KEY: SHOPIFY_API_SECRET_KEY, SCOPES: SCOPES, HOST_NAME: APP_URL.replace(/https:\/\//, ""), API_VERSION: "2022-01", IS_EMBEDDED_APP: true, SESSION_STORAGE: new Shopify.Session.CustomSessionStorage( sessionStorage.storeCallback, sessionStorage.loadCallback, sessionStorage.deleteCallback, ), });`

I tried updating the library about 3 month ago, I couldn't even authorize in Shopify after that. Made some researches and found out that I cannot touch [shopify-api] manually, it has to be installed by [@shopify/koa-shopify-auth] library, which uses old version of [shopify-api]. this is my issue actually, the problem can be solved by supporting newer [shopify-api] version
