### ISSUE TITLE
@shopify/koa-shopify-auth shopOrigin cookie not being refreshed again after quitting and re-opening chrome

### ISSUE THREAD

**Issue by mcunningham** [Shopify/koa-shopify-auth#18]
## Overview

I am using a pretty much standard react/node sales channel app modified from the tutorial [here](https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react). With the first installation of my app everything works, and the shopOrigin cookie is set using this `afterAuth` code block  
```js
  server.use(
    createShopifyAuth({
      apiKey: SHOPIFY_API_KEY,
      secret: SHOPIFY_API_SECRET_KEY,
      scopes: ["read_product_listings", "write_checkouts"],
      async afterAuth(ctx) {
        const { shop, accessToken } = ctx.session;
        ctx.cookies.set("shopOrigin", shop, {
          httpOnly: false,
          secure: true,
          sameSite: "none",
        });
 
        ctx.redirect("/");
      },
    })
  );
```

The app works ok as long as I don't quit chrome at any point after this. When I do quit out of chrome and revisit the Shopify Admin, I get a blank gray screen and the below error in a loop in the console, which ends up crashing chrome. 

```json 
name: "AppBridgeError", message: "APP::ERROR::INVALID_CONFIG: shopOrigin must be provided", action: undefined, type: "APP::ERROR::INVALID_CONFIG", stack: "AppBridgeError: APP::ERROR::INVALID_CONFIG: shopOrigin must be provided"}
```

My app has worked fine in the past after a chrome restart and I have not made any breaking updates to my knowledge. The past behavior was that when chrome is quit and the Shopify admin is re-launched it does a force full refresh, which I assume re-sets the shopOrigin cookie for AppBridge. I am no longer seeing that force refresh functionality, which I imagine is not setting the shopOrigin cookie and causing the error. Can anyone help me pinpoint this issue?

On a related note is there an update on when the [cookie-less experience](https://twitter.com/jmwind/status/1256249454430224386) is going to be released? This will have an impact on my current development and I am curious to know when it is coming.

## Consuming repo

> What repo were you working in when this issue occurred?
I am using the latest version of
@shopify/koa-shopify-auth

**Comment by rorz** [comment]
I have the same issue, which is a very annoying one to have to face in production! I've come up with a fix for now, if you're using [App Bridge React](https://www.npmjs.com/package/@shopify/app-bridge-react) (which I assume you are if you're following the React tutorial).

As you have found, the issue boils down to the fact that App Bridge React gets stuck in a loop if the `shopOrigin` cookie isn't present in its `config` prop object — hence the error message in the console.

I wanted to find a solution that is applicable directly to koa-shopify-auth, and I have found that if you delete the koa session `koa:sess` (or `koa.sess` in koa-session v6+) cookie, this triggers a successful reauth flow on the client. Attempting to emulate that — and since the koa session cookie is HTTP-only, I tried to create middleware that:
- Detects the lack of a `shopOrigin` cookie and then removes the koa session cookie — this didn't work
- Detects the lack of a `shopOrigin` cookie and then invalidates the koa session (via `ctx.session = null` as per [here](https://www.npmjs.com/package/@shopify/app-bridge-react)) — this also didn't work

So, I haven't got a solution for this repo — but on the client **what did work was this**:

First, to prevent App Bridge from going into a loop, check the `shopOrigin` cookie actually exists before rendering the rest of your root (or wherever the `<Provider />` component lives) component like so:
```jsx
const MyApp = ({ Component, pageProps }) => {
  // Your component set up / config
  
  // Assuming you use js-cookie:
  if (!Cookies.get("shopOrigin")) {
    // Cookie doesn't exist — you can choose to return something here or `null` even...
    return <h1>Loading, please wait...</h1>;
  }

  // The rest of your component render, with <Provider />
}
```

Now that we've stopped App Bridge from getting stuck, we can use an effect hook on the component that triggers a redirect to the inline auth flow if the cookie doesn't exist, like so:
```jsx
const MyApp = ({ Component, pageProps }) => {
  // Your component set up / config

  // Add a one-time effect hook
  useEffect(() => {
    const shopOrigin = Cookies.get("shopOrigin");
    if (!shopOrigin && window) {
      const { search } = window.location;
      const searchParams = new URLSearchParams(search);
      // Get the `shop` (same as `shopOrigin`) URL parameter from the embedded app
      if (searchParams.has("shop")) {
        // Redirect to the auth callback
        window.location = `/auth/inline?shop=${searchParams.get("shop")}`;
      }
    }
  }, []);

  if (!Cookies.get("shopOrigin")) {
    return <h1>Loading, please wait...</h1>;
  }

  // The rest of your component render, with <Provider />
}
```

This has solved the issue for me — at least in initial testing, whereby if I delete the `shopOrigin` cookie, it will trigger the reauth flow as above.

I can make no claims as to if this:
- Will cause any unintended side-effects
- Conforms to how Shopify recommends you perform (re)authentication

And, as above, it would be really nice to see this implemented in an official package — but it might even be needed on App Bridge React rather than koa-shopify-auth...

**Comment by DanieleSalatti** [comment]
@rorz that worked for me, at least in development - not sure if it'll be approved for prod but it'll do for now 👍

**Comment by thecodepixi** [comment]
Hi 👋🏻 This issue appears to be outdated, and most existing issues have been resolved by the latest release(s) of this library. I'm going to close this issue for now, but if you're still experiencing any problems with this library's code, please feel free to open a new issue. Thanks!
