### ISSUE TITLE
SameSite=None not working on oauth authorize

### ISSUE THREAD

**Issue by txreplay** [Shopify/koa-shopify-auth#66]
# Issue summary

Hi, I'm facing an issue with the third-party cookies on the oauth autorize flow. It seems that the oauth autorize route doesn't set `SameSite=None;Secure` parameters leading to the app not loading.

## Expected behavior

The `https://xxx.myshopify.com/admin/oauth/authorize` url should set cookies with `SameSite=None;Secure` parameters.

## Actual behavior

The `https://xxx.myshopify.com/admin/oauth/authorize` set cookies with `SameSite=Lax` (or without any) parameters. Causing app to reload three times before landing on apps list with error : This app can’t load due to an issue with browser cookies. The others routes (`https://example.com/?shop=xxx.myshopify.com`, `https://example.com/auth?shop=xxx.myshopify.com`, `https://example.com/auth/inline?shop=xxx.myshopify.com`, `https://example.com/auth/callback` all have corrects `SameSite=None;Secure` parameters since configured in our code

<img width="612" alt="screenshot" src="https://user-images.githubusercontent.com/4551108/110921924-695f2500-831f-11eb-94ae-cbebdeb94b77.png">

## Steps to reproduce the problem

Like I said, cookies set from our end are corrects since we followed the docs with : 

```
const cookieOptions = { httpOnly: false, secure: true, sameSite: 'none' }
const server = new Koa();
server.use(session(cookieOptions, server));
server.use(
        createShopifyAuth({
            apiKey: Shopify.Context.API_KEY,
            secret: Shopify.Context.API_SECRET_KEY,
            scopes: ['xxx'],
            afterAuth(ctx) {
                const { shop, scope, accessToken } = ctx.state.shopify;
                ACTIVE_SHOPIFY_SHOPS[shop] = scope;
                ctx.cookies.set("accessToken", accessToken, cookieOptions);
                ctx.cookies.set("shopOrigin", shop, cookieOptions);
                ctx.redirect(`/?shop=${shop}`);
            },
        }),
```

Thank you for your time and your help 🙂

**Comment by paulomarg** [comment]
Hi @txreplay, we're not using `SameSite=None` by design on this library, because browsers are making it increasingly difficult to use 3rd party cookies (cookies within iframes). You app should always make sure the user gets redirected to the OAuth URL at the top level of the browser, where cookies can be used reliably.

If you are creating an embedded app, the current recommended approach is to use [session tokens](https://shopify.dev/tutorials/authenticate-your-app-using-session-tokens) from App Bridge. You can also check out [our tutorial](https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react) which shows how this package helps you do that.

Hope this helps!
