### ISSUE TITLE
Multi page server side rendered NextJS app fails to open other pages

### ISSUE THREAD

**Issue by pratiknikam** [Shopify/koa-shopify-auth#76]
# Issue summary

I've managed my existing app to migrate to use sessions instead of cookies and initial index page loads fine. When I click on another menu items within embedded app, it re-initiates auth process and kicks ma back on index page.

![image](https://user-images.githubusercontent.com/2853953/111890231-e6dd0200-89bd-11eb-86b5-f72efd217fba.png)

**Main Packages:**

```
"@shopify/koa-shopify-auth": "^4.0.3"
"@shopify/app-bridge-utils": "^1.29.0"
"@koa/router": "^8.0.8"
"next": "^10.0.9"
"shopify-api-node": "^3.6.6"
```

## Expected behavior

Should be able to visit other pages within app.

## Actual behavior

When I click on other navigation items, does re-auth and kick me back to index page when I click on any navigation item

## Code

<details close>
<summary>server.js</summary>
<br>

```
import "@babel/polyfill";
import dotenv from "dotenv";
import "isomorphic-fetch";
import createShopifyAuth, { verifyRequest } from "@shopify/koa-shopify-auth";
import Shopify, { ApiVersion } from "@shopify/shopify-api";
import Koa from "koa";
import next from "next";
import Router from "koa-router";
import { MongoClient } from "mongodb";

dotenv.config();
const port = parseInt(process.env.PORT, 10) || 8081;
const dev = process.env.NODE_ENV !== "production";
const app = next({
    dev,
});
const handle = app.getRequestHandler();

Shopify.Context.initialize({
    API_KEY: process.env.SHOPIFY_API_KEY,
    API_SECRET_KEY: process.env.SHOPIFY_API_SECRET,
    SCOPES: process.env.SCOPES.split(","),
    HOST_NAME: process.env.HOST.replace(/https:\/\//, ""),
    API_VERSION: ApiVersion.October20,
    IS_EMBEDDED_APP: true,
    SESSION_STORAGE: new Shopify.Session.CustomSessionStorage(
        // not including implementation to save some space
        storeCallback,
        loadCallback,
        deleteCallback
    )
});

// Storing the currently active shops in memory will force them to re-login when your server restarts. You should
// persist this object in your app.
const ACTIVE_SHOPIFY_SHOPS = {};

MongoClient.connect(MONGODB_URI, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
}).then(async connection => {
    console.info(`Successfully connected to Mongo`);
    const mongodb = connection;

    app.prepare().then(async () => {
        const server = new Koa();
        const router = new Router();
        server.keys = [Shopify.Context.API_SECRET_KEY];
        server.use(
            createShopifyAuth({
                apiKey: SHOPIFY_API_KEY,
                secret: SHOPIFY_API_SECRET,
                scopes: [SCOPES],
                accessMode: "offline",
                async afterAuth(ctx) {
                    // Access token and shop available in ctx.state.shopify
                    const { shop, accessToken, scope } = ctx.state.shopify;
                    ACTIVE_SHOPIFY_SHOPS[shop] = scope;

                    if (!response.success) {
                        console.log(
                            `Failed to register APP_UNINSTALLED webhook: ${response.result}`
                        );
                    }

                    // Redirect to app with shop parameter upon auth
                    ctx.redirect(`/?shop=${shop}`);
                },
            })
        );

        const handleRequest = async (ctx) => {
            await handle(ctx.req, ctx.res);
            ctx.respond = false;
            ctx.res.statusCode = 200;
        };

        router.get("/", async (ctx) => {
            const shop = ctx.query.shop;

            // This shop hasn't been seen yet, go through OAuth to create a session
            if (ACTIVE_SHOPIFY_SHOPS[shop] === undefined) {
                ctx.redirect(`/auth?shop=${shop}`);
            } else {
                await handleRequest(ctx);
            }
        });

        server.use(require("./api"));

        router.get("(/_next/static/.*)", handleRequest); // Static content is clear
        router.get("/_next/webpack-hmr", handleRequest); // Webpack content is clear
        router.get("(.*)", verifyRequest({ accessMode: "offline" }), handleRequest); // Everything else must have sessions

        server.use(router.allowedMethods());
        server.use(router.routes());
        server.listen(port, () => {
            console.log(`> Ready on http://localhost:${port}`);
        });
    });
});
```
</details>

<details close>
<summary>_app.js</summary>
<br>

```
import ApolloClient from "apollo-boost";
import { ApolloProvider } from "react-apollo";
import App from "next/app";
import { AppProvider } from "@shopify/polaris";
import { Provider, useAppBridge } from "@shopify/app-bridge-react";
import { authenticatedFetch } from "@shopify/app-bridge-utils";
import "@shopify/polaris/dist/styles.css";
import translations from "@shopify/polaris/locales/en.json";

function MyProvider(props) {
  const app = useAppBridge();

  const client = new ApolloClient({
    fetch: authenticatedFetch(app),
    fetchOptions: {
      credentials: "include",
    },
  });

  const Component = props.Component;

  return (
    <ApolloProvider client={client}>
      <Component {...props} />
    </ApolloProvider>
  );
}

class MyApp extends App {

  render() {
    const { Component, pageProps, shopOrigin } = this.props;
    return (
      <AppProvider i18n={translations}>
        <Provider
          config={{
            apiKey: API_KEY,
            shopOrigin: shopOrigin,
            forceRedirect: true,
          }}
        >
          <MyProvider Component={Component} {...pageProps} />
        </Provider>
      </AppProvider>
    );
  }
}

MyApp.getInitialProps = async ({ ctx }) => {
  return {
    shopOrigin: ctx.query.shop,
    API_KEY: process.env.SHOPIFY_API_KEY
  };
};

export default MyApp;
```
</details>

---

## Checklist

- [X] Please delete the labels section before submitting your issue
- [X] I have described this issue in a way that is actionable (if possible)

**Comment by ilugobayo** [comment]
My problem is the same as yours, whenever I press one of the navigation items the app goes through the auth process all over again and displays the main page, if I add a route like this:

router.get("/index", handleRequest);

Then it works, but I think that's not the right way to do it since the request wouldn't be verified, and adding router.get("/index", verifyRequest({ accessMode: 'offline'}), handleRequest); has the same result as not having a route, the auth process happens all over again.

I tried to follow the tutorial in the Shopify docs, about how to build your user interface with Polaris, in which they tell you to add a ClientRouter component but adding it didn't solve the issue, I actually tested the code on that [branch](https://github.com/Shopify/shopify-app-node/tree/tutorial_build_interface_with_polaris) but the code doesn't seem to work, because whenever I press one of the navigation items, I get a `Bad request` message in the embedded app and nothing happens, I don't know what could be the issue, I've been searching for a solution but no luck yet.

**Comment by valorloff** [comment]
Confirm it!
In my opinion, the problem is related to the auth token is lost after route to index page. 
need to save it and use it for following routing. But I still have no idea how.... any ideas?

**Comment by pratiknikam** [comment]
I was able to replicate this on current https://github.com/Shopify/shopify-app-node with the help of Shopify CLI. If you aren't using Shopify CLI, you can simply clone the project and follow setup instructions.

**Steps to reproduce:**

1. shopify create project jwt_test
2. shopify serve
3. Begin app installation on development store.
3. App does authenticate well and loads index page fine. (It's damn slow btw as mentioned in https://github.com/Shopify/shopify-app-node/issues/584)
4. Go back to codebase and create `pages/indexCopy.js` and just copy paste contents of `pages/index.js` in it.
5. Go to partners dashboard and add a navigation menu for newly created app.
6. Navigate to app and then navigate to index copy
7. You would see it would re-authenticates again and then kicks you back to index.js

![image](https://user-images.githubusercontent.com/2853953/111916480-826b8280-8a51-11eb-9540-f7516d3845a6.png)

![image](https://user-images.githubusercontent.com/2853953/111916504-a4650500-8a51-11eb-9c8e-764ac808698a.png)

**Comment by valorloff** [comment]
Confirmed!
App does authenticate well and loads index page fine, but other navigations results 'bad request'. Reload page results 'InternalServerError: Cannot complete OAuth process. Could not find an OAuth cookie for shop url:' and so on

**Comment by ilugobayo** [comment]
@paulomarg could you please shed some light on this matter? It would be highly appreciated.

**Comment by tommy921092** [comment]
I also faced the same issue, when I navigate to other pages except index, it simply shows "bad request". This can be simply replicated by adding new pages on starter app created by shopify cli. Please advise.

**Comment by pratiknikam** [comment]
**Quick update:** This seems to be the issue around `verifyRequest` middleware. Following **doesn't fix** the re-auth issue but at least loads navigated page after 10 seconds or so.

Change 
```
router.get("(.*)", verifyRequest({ accessMode: "offline" }), handleRequest);
```
to 
```
router.get("(.*)", handleRequest);
```

**Note:** This isn't recommended solution.

@paulomarg would be great if you can look into this at your earliest convenience. Thanks a lot in advance :)

**Comment by paulomarg** [comment]
Hey folks! I think @pratiknikam is right that `verifyRequest` would trigger that behaviour if your app is using server-rendered pages, because it would expect to find the JWT in the `Authorization` header, if that request made it to the server - which won't happen for page navigation.

As mentioned [in the tutorial](https://shopify.dev/tutorials/build-a-shopify-app-with-node-and-react/build-your-user-interface-with-polaris#add-the-client-router), the `ClientRouter` will prevent your app from making such requests by handling URL changes locally.

**Note**: I suspect the tutorial's code for that step might be using a slightly outdated version of `koa-shopify-auth`. I'll make sure it's working as expected so you can use it as an example.

If you **have** to do a page reload when the URL changes, you should consider the following:
- That action should behave like the `/` endpoint, so it doesn't use `verifyRequest`, but it should make sure to check `ACTIVE_SHOPIFY_SHOPS` if the user can go straight to that page.
- Not using `verifyRequest` means the endpoint is **unauthenticated**, so it **should not** load any sensitive information because it may be accessed by other users. You should load a page skeleton and use `authenticatedFetch` to grab any sensitive data.
- You may need to make sure the `shop` param is in the URL

**Comment by pratiknikam** [comment]
@paulomarg thanks for additional helpful insights :) Adding `ClientRouter` did help me here. Another question I have is around navigations which happen on client side.

If you look at following Polaris component. Whenever merchant clicks on "Create now", that throws 302 Found with Location being /auth route which then throws 400.

```
<CalloutCard
    title="Create Element"
    primaryAction={{
        content: "Create now",
        url: "/element/new"
 }}
>
```

![image](https://user-images.githubusercontent.com/2853953/112403574-0e490d00-8ce5-11eb-9915-49c19349d55c.png)

**Comment by ilugobayo** [comment]
@pratiknikam can you share the code that worked for you? Last week I tried with the `ClientRouter` component for various days to make it work but I just couldn't, guess I'm doing something wrong

**Comment by valorloff** [comment]
the clientRouter in the  tutorial code was originally, this does not affect in any way, problem does't solved! 
After install app succesfully loaded index page, following navigations by nav links impossible, anybody confirm it?

**Comment by pratiknikam** [comment]
@valorloff I was originally missing `ClientRouter`. After adding it like below, I can at least navigate to different pages. I'm still having an issue I mentioned just couple threads above though around client side navigation. URL doesn't change when I try to navigate client side with the help of Router or any Polaris component.

<details close>
<summary>Updated _app.js</summary>
<br>

```
import ApolloClient from "apollo-boost";
import { ApolloProvider } from "react-apollo";
import App from "next/app";
import { AppProvider } from "@shopify/polaris";
import { Provider, useAppBridge } from "@shopify/app-bridge-react";
import { authenticatedFetch } from "@shopify/app-bridge-utils";
import "@shopify/polaris/dist/styles.css";
import translations from "@shopify/polaris/locales/en.json";
import ClientRouter from "../components/ClientRouter";

function MyProvider(props) {
  const app = useAppBridge();

  const client = new ApolloClient({
    fetch: authenticatedFetch(app),
    fetchOptions: {
      credentials: "include",
    },
  });

  const Component = props.Component;

  return (
    <ApolloProvider client={client}>
      <Component {...props} />
    </ApolloProvider>
  );
}

class MyApp extends App {

  render() {
    const { Component, pageProps, shopOrigin } = this.props;
    return (
      <AppProvider i18n={translations}>
        <Provider
          config={{
            apiKey: API_KEY,
            shopOrigin: shopOrigin,
            forceRedirect: true,
          }}
        >
          <ClientRouter />
          <MyProvider Component={Component} {...pageProps} />
        </Provider>
      </AppProvider>
    );
  }
}

MyApp.getInitialProps = async ({ ctx }) => {
  return {
    shopOrigin: ctx.query.shop,
    API_KEY: process.env.SHOPIFY_API_KEY
  };
};

export default MyApp;
```
</details>

**Comment by paulomarg** [comment]
@pratiknikam The 302 response from the first request means it was redirected to `/auth`, most likely because of `verifyRequest`.

Looking at your updated `_app` file, I think you need to move your `<ClientRouter />` line one level up, so it's between `<AppProvider>` and `<Provider>`.

**Comment by valorloff** [comment]
Routing like `redirect.dispatch(Redirect.Action.APP, {path: '/edit-collection', newContext: true});` works ok, but routing by nav links return bad request crash.
Do I understand correctly that the clientRouter makes Embedded App Navigation links client-side?

**Comment by pratiknikam** [comment]
@paulomarg good catch! Now next issue I'm having is that page URL is not updating with page I'm navigating to. These are pages which are **not** set in app navigation but part of app. (Ex. Creating new block)

Agree with what @valorloff said around navigation. I'm seeing similar issue.

**Doesn't work:** (does redirect but doesn't update URL)
```
router.push(`/element/new`);
```
or
```
<CalloutCard
    title="Create Element"
    primaryAction={{
        content: "Create now",
        url: "/element/new"
 }}
>
```

**Does work:** (does redirect and also updates URL)
```
redirect.dispatch(Redirect.Action.APP, {path: '/element/new', newContext: true});
```

**Comment by Crunchyman-ralph** [comment]
@pratiknikam you seem to have solved a majority of the issue, could you share your `ClientRouter` Component. I can't seem to figure out which packages you are using for the `redirect` and for the `Redirect`

are you using these packages?
`
import redirect from "@shopify/koa-shopify-auth"
import {Redirect} from "@shopify/app-bridge/actions"
`

**Comment by valorloff** [comment]
My issue with "index" page solved thanks to this [hint](https://github.com/Shopify/shopify-app-node/issues/585#issuecomment-807481767)

**Comment by ivorpad** [comment]
You need two things, the `ClientRouter` component and `RoutePropagator`

```javascript

import React from 'react';
import { withRouter } from 'next/router';
import { ClientRouter as AppBridgeClientRouter } from '@shopify/app-bridge-react';

function ClientRouter(props) {
  console.log(props);
  
  const { router } = props;
  return <AppBridgeClientRouter history={router} />;
}

export default withRouter(ClientRouter);
```

```javascript
const RoutePropagator = () => {
  const router = useRouter();
  const { route } = router;
  const appBridge = React.useContext(AppBridgeContext);

  useEffect(() => {
    appBridge.subscribe(Redirect.ActionType.APP, ({ path }) => {
      Router.push(path);
    });
  }, []);

  return appBridge && route ? (
    <ShopifyRoutePropagator location={route} />
  ) : null;
};
```

This has a tradeoff, you will lose the `query` with hmac, shop and other params when you navigate to other pages but you can grab that from the `session` object.

**Comment by valorloff** [comment]
> ```js
> a[[.subscribe(Redirect.ActionType.APP, ({ path }) => {
>       Router.push(path);
>     });
> ```
Hi!
Please, explain this section

**Comment by ivorpad** [comment]
@valorloff A typo. Fixed.

**Comment by valorloff** [comment]
Did you mean add RoutePropagator to _app.js?
```
<Provider config={config}>
                    <RoutePropagator />
                    <ClientRouter/>
                    <AppProvider i18n={translations}>
                        <MyProvider>
                            <Component {...pageProps} />
                        </MyProvider>
                    </AppProvider>
                </Provider>
```

**Comment by Crunchyman-ralph** [comment]
@ivorpad did you mean to replace `appBridge` by `app` in 
`
return appBridge && route ? (
    <ShopifyRoutePropagator location={route} />
  ) : null;
`

and where do you inject this component ?
in the `_app.js` next to the `<ClientRouter/>` ?

**Comment by barisozdogan** [comment]
Although i followed above suggestions, still I'm not able to do routing by using below app bridge action.

> Redirect.create(app).dispatch(Redirect.Action.APP, { path: redirectionUrl, newContext: true });

The weird part is i can't see above dispatched action when i checked redux devtools for app bridge.

```
import {useEffect, useContext} from 'react';
import Router, { useRouter } from "next/router";
import { Context as AppBridgeContext } from "@shopify/app-bridge-react";
import { Redirect } from "@shopify/app-bridge/actions";
import { RoutePropagator as ShopifyRoutePropagator } from "@shopify/app-bridge-react";

const RoutePropagator = () => {
  const router = useRouter(); 
  const { route } = router;
  const appBridge = useContext(AppBridgeContext);

  useEffect(() => {
    appBridge.subscribe(Redirect.ActionType.APP, ({ path }) => {
      Router.push(path);
    });
  }, []);

  return appBridge && route ? (
    <ShopifyRoutePropagator location={route} app={appBridge} />
  ) : null;
}

export default RoutePropagator;
```

```
import { withRouter } from 'next/router';
import {ClientRouter as AppBridgeClientRouter} from '@shopify/app-bridge-react';

function ClientRouter(props) {
  const {router} = props;
  return <AppBridgeClientRouter history={router} />;
};

export default withRouter(ClientRouter);
```

```
import ApolloClient from "apollo-boost";
import { ApolloProvider } from "react-apollo";
import App from "next/app";
import { AppProvider } from "@shopify/polaris";
import { Provider, Context } from "@shopify/app-bridge-react";
import { Redirect } from '@shopify/app-bridge/actions';
import { authenticatedFetch } from "@shopify/app-bridge-utils";
import "@shopify/polaris/dist/styles.css";
import translations from "@shopify/polaris/locales/en.json";
import ClientRouter from '../components/ClientRouter';
import RoutePropagator from '../components/RoutePropagator';
import { Provider as ReactReduxProvider } from 'react-redux';
import { useStore } from '../store/store';

function userLoggedInFetch(app) {
  const fetchFunction = authenticatedFetch(app);

  return async (uri, options) => {
    const response = await fetchFunction(uri, options);

    if (response.headers.get('X-Shopify-API-Request-Failure-Reauthorize') === '1') {
      const authUrlHeader = response.headers.get('X-Shopify-API-Request-Failure-Reauthorize-Url');

      const redirect = Redirect.create(app);
      redirect.dispatch(Redirect.Action.APP, authUrlHeader || `/auth`);
      return null;
    }

    return response;
  };
}

class MyProvider extends React.Component {
  static contextType = Context;

  render() {
    const app = this.context;

    const client = new ApolloClient({
      fetch: userLoggedInFetch(app),
      fetchOptions: {
        credentials: "include",
      },
    });

    return (
      <ApolloProvider client={client}>
        {this.props.children}
      </ApolloProvider>
    );
  }
}

class MyApp extends App {
  render() {
    const { Component, pageProps, shopOrigin } = this.props;
    
    const config = { apiKey: API_KEY, shopOrigin, forceRedirect: true };
    const store = useStore({});

    return (
      <Provider config={config}>
        <ClientRouter />
        <AppProvider i18n={translations}>
          <RoutePropagator />
          <ReactReduxProvider store={store}>
            <MyProvider>
              <Component {...pageProps} />
            </MyProvider>
          </ReactReduxProvider>
        </AppProvider>
      </Provider>
    );
  }
}

MyApp.getInitialProps = async ({ ctx }) => {
  return {
    shopOrigin: ctx.query.shop,
    API_KEY: process.env.SHOPIFY_API_KEY
  };
};

export default MyApp;

```

**Comment by valorloff** [comment]
I think the class components should be redone to functional for comfortable use hooks

**Comment by Crunchyman-ralph** [comment]
@barisozdogan 
I decided to not use the built in shopify navigation and instead use my own polaris navigation.
This is what the code looks like

```
import {useRouter} from 'next/router'

const router = useRouter()
Router.push({
        pathname: url,
        query: router.query
    })
```

**Comment by ilugobayo** [comment]
Well, I finally was able to make the tutorial code work, but now trying to implement that solution in my app gives me the next problem. Because I need to load some data from the server for which I use my custom routes, namely 

On server.js:

```
router.get('/api/get-paid-status', async (ctx) => {
const referer = ctx.headers.referer;
    const shopDomain = referer.substring(referer.indexOf('&shop=') + 6, referer.indexOf('&timestamp'));

    try {
      const paidStatus = await dbGetHelper.getPaidStatus(shopDomain);

      if (paidStatus !== undefined && paidStatus !== null) {
        ctx.body = {
          data: paidStatus
        };
      } else {
        ctx.body = {
          data: null
        };
        logger.error(stringInject.default(logMessages.serverPaidStatusUndefined, [shopDomain]));
      }
    } catch (err) {
      ctx.body = {
        data: null
      };
      logger.error(stringInject.default(logMessages.serverGetPaidStatusCatch, [shopDomain, err]))
    }
  });
```

Which I call from a page, in this case, a page that is not index, backfill.js

`const paidStatus = await this.makeGetRequest('/api/bayonet/get-paid-status/');` 

The makeGetRequest is as follows to hit the route in the server

```
makeGetRequest = async (endpoint) => {
    const result = await fetch(endpoint,
      {
        method: 'GET',
        headers: {
          'Accept': 'application/json',
        },
      })
      .then(resp => resp.json())
      .then(json => {
        return json;
      });

    return result;
  };
```

If the app has been just loaded, it will show the index page with no issues and every request to the server will work as expected, the referer will contain the shopOrigin and everything, no issues at all, but if I try to use the navigation buttons, nothing will load, somehow I lose the authentication/session info?

I think this is where the problem lies, because checking the ngrok log and the console on Chrome, it tries to go to the auth page all over again, so my skeleton page never disappears, and as you can see, since I started to develop the app I had been using ctx.headers.referer to get the shopOrigin and then proceed to perform the corresponding tasks, but now with the `ClientRouter` whenever I press on the navigation buttons, including the one linked to the `'/'` endpoint, the referer only has the URL of my server and the endpoint, namely `https://mylocalserver.ngrok.io/backfill`, no hmac, no shop, nothing.

If I try to go directly to the page from the address bar, not using the navigation buttons, I get `InternalServerError: Cannot complete OAuth process. Could not find an OAuth cookie for shop url`

I've been searching for so many days for a clear example on how to handle this, since the session storage has been already addressed and solved, this is the only part that I'm missing to make my app work again like it used to before the required changes for the app review.

I would endlessly appreciate anyone that could guide me on this, thank you.

**Comment by pratiknikam** [comment]
@ilugobayo Did you upgrade to [latest version](https://github.com/Shopify/koa-shopify-auth/releases/tag/v4.1.2) of `koa-shopify-auth: 4.1.2`? If so, please delete your iFrame cookies. I saw similar issue and clearing cookies did help me resolve it.

**Comment by ilugobayo** [comment]
@pratiknikam Just upgrade the `koa-shopify-auth` version and tried to test it using incognito mode, to avoid any old cookies stored, same situation. Do you make any requests to the server from any of your pages? If so, how did you manage to authenticate them?

**Comment by barisozdogan** [comment]
I finally fix the issue. Let me briefly explain here as well, as someone might be experiencing same situation. 

In my case, the problem was came out during callback from twitter.
I defined a route within server.js to be able to handle twitter callback request. 
 ```
const handleRequest = async (ctx) => {
    await handle(ctx.req, ctx.res);
    ctx.respond = false;
    ctx.res.statusCode = 200;
  };

router.get("/oauth/callback/twitter", async (ctx) => {
    const shop = ctx.cookies.get('shop');
    ctx.redirect(`/auth?shop=${shop}`);
    ctx.request.url = ctx.request.url + "&shop=" + shop
    await handleRequest(ctx);
  }); 
```
The problem for that route was to not checking whether auth completed successfully or not right after redirect. 
Because once oauth completed, it will be hit the same route again along the known parameters such as "hmac" and other stuff. So if  i don't check hmac, it would be trying to re-authenticate again for an already authenticated request and it will end up with recursion.  Corresponding nextjs page would be shown for this route at the end but shopify app bridge could not be initialized properly. This will lead to  dispathing a Redirect action to the non created app bridge instance. When I check redux dev tools for the app bridge's state, I was not able to see dispatched redirect action which proofs my case.

In order to fix issue i changed my route as below;

```
router.get("/oauth/callback/twitter", async (ctx) => {
    if (!ctx.request.query.hmac) {
      const shop = ctx.cookies.get('shop');
      ctx.redirect(`/auth?shop=${shop}`);
      ctx.request.url = ctx.request.url + "&shop=" + shop
    }
    await handleRequest(ctx);
  });
```

After this, I was able to monitor that app bridge created properly and Redirect started to working (Also observed successfull dispatched redirect action to the app bridge state within redux devtools)
I hope it can help to your problems as well.

Thanks,

**Comment by hedgerh** [comment]
Would all of this be solved if you weren't trying to handle navigation outside of your Next.js app?  It seems like Shopify's nav links don't work well if an app is using a client side router internally, like Next.js is.  When I had issues with navlinks in the past, I thought it would have been nice if the navbar was a component that I could pull in to my app to handle linking properly.

**Comment by paulomarg** [comment]
Hey @mayrsascha, thank you for the detailed post - this has come up a couple of times recently (https://github.com/Shopify/shopify-app-node/issues/619 and https://github.com/Shopify/shopify-app-node/issues/621), and your comment covers most of those questions, so thank you for that! I'll see if I can shed some light on the reasons behind this change below.

I think you're very much on the right path - `getServerSideProps` lacks the `Authorization` header, so it will not be able to call `loadCurrentSession` from the request on embedded apps (this is the problem you were seeing @SerhiDi and @tolgap).

Unfortunately, browsers are making it very difficult to use cookies (or any sort of client-side storage) when a page runs within an iframe, so there is not much we can do about that other than move away from cookies and start using JWT. With that, we can work with iframes even if browsers stop allowing 3rd party cookies altogether (which isn't a bad thing!).

Previously, the session cookie would be sent along with the server side props request so we could load the session data, but that is no longer an option, which makes life harder for server-side rendered apps. With session tokens, we can authenticate requests using `authenticatedFetch` instead of the session cookie, but that can only happen **after** the page is able to run the Javascript code to start up App Bridge. That is why SSR is tricky, because it involves two trips to the server (one for the page skeleton that builds App Bridge, and one for the sensitive data).

Out of the options you propose:
1. That is the current direction we're suggesting partners take. Client-side rendering works better for embedded apps because you can build your App Bridge `app` once and use that (and the `authenticatedFetch` method it brings) throughout your app. Otherwise, every page request that reaches the server needs to do a second round-trip to get the data, as I mentioned above.
2. Any solution that allows you to use `authenticatedFetch` + `verifyRequest` would allow you to load your data, as far as the backend library is concerned. You can handle URL changes on the client side using the [`ClientRouter` from App Bridge](https://shopify.dev/tools/app-bridge/react-components/client-router), but you'd still need to re-write the API endpoints as in option 1 instead of relying on `getServerSideProps`.
3. This would work as far as loading the data goes, but having the token in the URL would be less secure, since it would be easier to intercept than the header, so that is not ideal.

I hope this helps make things a little bit clearer!

**Comment by mayrsascha** [comment]
@paulomarg Thanks for the detailled answer, this makes things clearer for me!

After reading your answer, I decided to go for option 1. Option 3 seemed easy to implement but you are right that it's indeed less secure ([if anyone is interested why, read this](https://www.fullcontact.com/blog/2016/04/29/never-put-secrets-urls-query-parameters/)).

**Comment by sroettering** [comment]
I also have the problem with the auth route not receiving a shop query parameter. However, I am wondering why the app redirects to auth at all. I have the setup mentioned above using ClientRouter and RoutePropagator. My main navigation is working. On the index page I fetch some data and if something is missing I want to redirect to another page (that is not part of the main navigation). I'm doing a `router.push` using the next/router. For whatever reason the page is not loaded (302 returned) and a call to the /auth route is done instead. I also tried using the Redirect action from AppBridge.
What am I doing wrong?

**Comment by MedElloumi** [comment]
Hey, It took me some time to discover what I was doing wrong, I hope this will help someone (I am still not sure if what I was doing is wrong xD)

file structure: /pages/index.js

Within partner account, I set the Home Menu Item to: https://${myAddress}.com/index

When I open the application for the first time everything is working as expected when I switch to another page also, when I click the Home Menu Item I receive the following error message: Expected a valid shop query parameter !

I checked the Nngrok console and it looks that the application was trying to resolve : https://${myAddress}.com/index/index.js !!

What I did mainly is changing the Menu Item link from https://${myAddress}.com/index to https://${myAddress}.com

**Comment by offsec1** [comment]
Hey,

I'm still facing some issues using ` redirect.dispatch(Redirect.Action.APP, {path: '/settings', newContext: true}); `. I created a ClientRouter and also a RoutePropagator like mentioned in this thread. Sometimes I'm able to ridirect properly but most of the times I'm not which leads to the "Expected a valid shop query parameter" error. I can't seem to figure out why it sometimes works since I'm not changing anything. Any help is appreciated.

**Comment by chaddjohnson** [comment]
I was getting the "Expected a valid shop query parameter" due to my app strangely making requests to "/auth" during runtime, and I was able to make this error go away by passing `returnHeader: true` to `verifyRequest()`.

**Comment by doctarock** [comment]
We are facing the same issue, it is hard to pin down as it is not clear if the issue lies within the koa router, or the app bridge itself.

We have managed to leverage some caching in the router to get an extended life out of it, but the problem still exists once auth sessions start to expire, we have sunk days into this problem, there are many discussions online about this issue here and on the koa github, none of which seem to lead to a working fix, fingers crossed this gets resolved soon.

**Comment by FredyC** [comment]
I think I have a solution that seems to be working. First, a mentioned ClientRouter, but I have made it like this.

```ts
import { useRouter } from "next/router";

import {
  useClientRouting,
  useRoutePropagation,
} from "@shopify/app-bridge-react";

export function ClientRouter() {
  const router = useRouter();

  useClientRouting(router);
  useRoutePropagation(router.asPath);

  return null;
}
```

The `useClientRouter` is internally watching for the redirect action, so I made this small hook that I use. The important part is `router.asPath` which adds the query arguments including shop and host so the `verifyRequest` on serverside works.

import { useRouter } from "next/router";

import { useAppBridge } from "@shopify/app-bridge-react";
import { Redirect } from "@shopify/app-bridge/actions";

```ts
export function useAppRedirect() {
  const app = useAppBridge();
  const router = useRouter();

  return (path: string) => {
    const redirect = Redirect.create(app);
    redirect.dispatch(Redirect.Action.APP, `${path}${router.asPath}`);
  };
}
```

And as for Polaris components, I made this wrapper component which I then set like `<AppProvider linkComponent={PolarisLink}>`.

```ts
function PolarisLink({
  url,
  children,
  external,
  ...rest
}: LinkLikeComponentProps) {
  if (external) {
    return (
      <a href={url} {...rest}>
        {children}
      </a>
    );
  }
  const redirect = useAppRedirect();
  return (
    <a
      href={url}
      onClick={(e) => {
        e.preventDefault();
        redirect(url);
      }}
      {...rest}
    >
      {children}
    </a>
  );
}
```

Hopefully, this helps some of you.

**Comment by robotshatemonkeys** [comment]
> shopOrigin
Hello everybody, I have the same issue and tired to follow your solution. 
I spent days with this problem and it's driving me crazy.  
During client navigation I loose the query data. 
Do you have any example of what would be the final solution ? @isaacbowen
