### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by robotshatemonkeys** [Shopify/koa-shopify-auth#9]
I'm using this library koa-shopify-aut to get our OAuth2 on shopify,
but we loose permission access after ( 403 Forbidden ) after 1-2 days.

No idea why this is happening, if it is a bug and we are getting a temporary token instead of the permanent one, or we are doing something wrong.

I still able to get Shop info, but I loose access to requested permission such read_products

**Comment by nico-medina** [comment]
Hi guys, anyone found a solution for this? I need to have an online access token for graphql request and an offline token for webhooks. Which would be the approach for that case? 

Thanks!

**Comment by paulomarg** [comment]
Hey @nico-medina, this is actually working as designed. Online access tokens expire after 1 day and follow the user's permissions, so you might get both 403 and 401 responses from Shopify, and both will mean that you need to go through the OAuth process again to renew the user's access rights.

You can refer to our [documentation on access modes](https://shopify.dev/concepts/about-apis/authentication#api-access-modes) for more information on how each access mode works.

This is actually an old ticket, and this package has undergone major changes since it was asked, so code mentioned here might no longer apply. Since this is not a bug in the library, I'm closing this issue
